version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: pizzitalia
    container_name: pizza_web
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    env_file:
      - .envs/.local/.django
    command: ["/wait_for_db.sh", "/start"]
    volumes:
      - media:/app/media/

  db:
    restart: always
    image: postgres:12
    container_name: pizza_db
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=pizzitalia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  media:

