version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: pizzitalia
    container_name: pizza_web
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .envs/.local/.django
    command: "/start"
    volumes:
      - media:/app/media/
      - ./src:/app  # Ensure the source code is mounted correctly

  db:
    image: postgres:12
    container_name: pizza_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=pizzitalia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres   

volumes:
  postgres_data:
  media:
