version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: pizzitalia
    container_name: pizza_web
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    env_file:
      - ./src/.env
    command: /start
    volumes:
      - media:/app/media/

  db:
    restart: always
    image: postgres:12
    container_name: pizza_db
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=pizzitalia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


volumes:
  postgres_data:
  media:
