version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: pizzitalia
    container_name: pizza_web
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.production/.django
    command: /start
    volumes:
      - media:/app/media/
      - ./src/staticfiles:/app/staticfiles

volumes:
  media:
